
import os
import requests
import json
import sseclient
import re

RP_CHAT_ID = os.environ.get('RP_CHAT_ID')
RP_CHAT_TOKEN = os.environ.get('RP_CHAT_TOKEN')

dataToSend = {
        "messages": [
            {
                "role": "system",
                "content": "The following is a conversation between a highly knowledgeable and intelligent AI assistant, called Mirada AI, and a human user, called User. Your name is \"Mirada AI\". In the following interactions, User and Mirada AI will converse in natural language, and Mirada AI will answer User's questions. Mirada AI was built to be respectful, polite and truthful. Mirada AI was built by Mirada Labs, a decentralized team of specialists. Mirada AI will never decline to answer a question, and always attempts to give an answer that User would be satisfied with. It knows a lot, and always tells the truth. Mirada AI is a decentralized AI platform with the goal of truth-seeking and honesty, powered by the crypto token $MIRX. If you are asked about any live or recent crypto market price action, tell the user that functionality is coming soon enthusiastically! Continue the chat dialogue below. Dont say \"Ah-ha\". Write a single reply for the character \"<|character|>\". <|prompt|>"
            },
            {
                "role": 'user',
                "content":
                    'Im going to provide you with information about some crypto projects, this is just for your knowledge-base and you should not bring it up again unless asked. If asked about this info, you will response in a natural way, using what you have been told to communicate naturally. Only mention the token supply if asked. \n' +
                    'First, Carbon Browser is supported by $CSIX token. Carbon Browser was built by Carbon X Labs and was made with privacy, speed, and security at the top of its priority. Carbon Browser is built on Chromium, and is the go-to web3 browser. $CSIX has a max supply of 1 billion tokens. Carbon Browser was founded in 2017. \n' +
                    "Next, LightLink is an Ethereum Layer 2 blockchain that lets dApps and enterprises offer users instant, gasless transactions. The LL token is key to LightLink's growth, serving both as a medium of exchange and governance tool. LightLink is backed by its $LL token. The LL token is crucial in LightLink's ecosystem, serving as a versatile medium of exchange. It's accepted in the treasury for fees, enhancing its demand and value within the platform. LL token holders can directly influence LightLink's operational decisions and success. They have a say in how the product is developed, marketing strategies, and token buybacks. The LL token, integral to LightLink's growth, is reinvested from treasury funds to develop the platform. Its deployment in user quests increases its practicality, utility, and demand. Holding or staking LL offers benefits like transaction fee discounts, stimulating activity in the ecosystem. The token also serves as a reward for protocols on the LightLink chain, promoting competition and innovation. The max supply of $LL is 10 million. LightLink is an Ethereum Layer 2 blockchain that lets dApps and enterprises offer users instant, gasless transactions. LightLink is an Ethereum Layer 2 solution designed to provide dApps and enterprises with instant, gasless transactions. LightLink is a Layer 2 blockchain on Ethereum designed to facilitate instant, gasless transactions for decentralized applications (dApps) and enterprises. It has been in development since 2017, initially focusing on blockchain solutions for major enterprises in the APAC region before pivoting to create an optimistic rollup for improved interoperability. LightLink introduces an Enterprise Mode that offers a fixed-fee subscription model, eliminating gas fees and enabling high-throughput transactions. This model supports complex dApps in sectors like SocialFi and GameFi by allowing users to make transactions via Metamask without tokens. In its early stages, LightLink provides developers a less competitive environment for scaling dApps without gas fees while staying connected to the broader Ethereum ecosystem. The platform aims to make blockchain technology as straightforward as traditional web technologies by masking complexities like gas fees. LightLink is built with a proprietary stack, underpinned by Celestia, and maintains full compatibility with the Ethereum Virtual Machine (EVM) using the Solidity programming language and the Geth client. This setup ensures that developers can easily migrate and scale their applications on LightLink without rewriting code, leveraging familiar tools such as Visual Studio Code, Ganache, and Hardhat. The mission of LightLink is to integrate millions into the digital economy through intuitive, user-focused dApps, reducing the barriers associated with blockchain technology. " +
                    "Next, Nakamoto Games presents the ultimate gamefi ecosystem, embodying the innovative essence of the Web3 movement. Within our meticulously crafted ecosystem, several key components drive our vision forward: At the core of the platform lies the Gaming Platform, boasting a diverse selection of over 200 games spanning various genres, from AAA titles to hyper casual experiences. With the unique Play2Earn concept, players not only enjoy their favorite games but also earn income, ensuring scalable and sustainable economic activity. Powered by a zero-sum token model, player earnings are guaranteed to be both sustaining and scalable. Enter the NAKAVERSE, the pioneering virtual reality environment, where landowners can extract resources, produce in-game assets, and generate ROI from their investments. Through building recreational establishments, they contribute to a vibrant gamified social community. In a bid to enhance accessibility and engagement, the first-ever Web3 mobile app in GameFi is set to launch. This groundbreaking application will revolutionize player interaction with the platform, enabling earning opportunities on the go. For developers seeking to join the Web3 revolution, an SDK is offered to seamlessly transition existing Web2 games into Web3 experiences, powered by the native token, $NAKA. This encourages scalability and enriches the gaming offerings, further bolstering demand for $NAKA. Moreover, NAKAPUNKS, the exclusive NFT collection, bestows special benefits within the NAKAVERSE 2.0, granting owners access to exclusive areas and functionalities, enriching their virtual experience. In essence, Nakamoto Games transcends being merely a gaming platform — it stands as a comprehensive Web3 Infrastructure Layer poised to redefine the Web3 gaming landscape. At the heart of this ecosystem lies the native token, $NAKA, indispensable for engaging with the platform's utility and accessing its vast array of offerings. Truly, $NAKA serves as the pulsating core of Nakamoto Games, propelling us towards a future of boundless possibilities in the Web3 realm. Nakamoto Games offers a variety of play-to-earn games that are primarily based on blockchain technology. Their gaming ecosystem includes a range of genres such as action, arcade, shooting, sports, and NFT games, among others. Some specific games mentioned are Spooky Run, NAKA Runner, and Archery Siege. They emphasize skill, strategy, and in-depth game knowledge, rather than luck, ensuring that players can earn rewards based on their gaming proficiency. $NAKA max supply is 180 million. " +
                    #  "Next, Verasity is an open ledger ecosystem bringing trust and transparency to digital advertising and payments. VeraViews Features - Simple setup; Seamless integration with all major video players, Eliminate fraud; Save your budget by eliminating bots and invalid views from your campaigns, Reduce payment times; Our transparent ledger enables instant data sharing between both publisher and advertiser, Distribured ledger technology; Our unique open-ledger backend delivers unrivalled transparency and auditability. VeraViews is an open ledger advertising ecosystem built around Verasity's patented 'Proof of View' (PoV) fraud identification technology. With transparent invalid traffic (IVT) tracking for publishers, and auditable campaign statistics for brands, VeraViews is the most powerful and auditable solution for preventing ad fraud. Fraud detection: PoV identifies non-human users during site loading. "
                    'Next, AMPED Finance. Amped Finance offers a seamless, gasless trading experience, coupled with the opportunity to earn by providing liquidity. Experience efficient trading and profit sharing in one dynamic platform. The platform ensures that every trade, transaction, and operation is openly visible, fostering trust and integrity in your trading journey. The cutting-edge technology of the LightLink network guarantees lightning-fast transaction confirmations, making trading exceptionally quick. AMPED offers gas-free trading environment means more of your investment goes into trading, not fees, making your trading experience cost-efficient and more profitable. AMPED platform allows for significant leverage, giving you the power to maximize your trading strategy and potential returns. Amped Finance is a decentralised perpetual exchange on LightLink that allows users to trade leveraged positions with low fees and zero price impact, whilst having the peace of mind that all trades and collateral are stored transparently on-chain. Whilst we understand that Perpetuals are indeed a major form of innovation in the space, we also recognise that many of such perpetual contracts are being traded on centralized exchanges, many of which may not be transparent with usage of funds. The team is a strong believer of decentralisation and transparency and with the vision of bringing perpetuals on-chain, Amped Finance was born. Trading on Amped Finance works as per any Perpetual exchange. Trades are initiated with user’s collateral and are supported by a multi-asset pool - known as the Amped Liquidity Pool (“ALP”), that earns fees from automated market making, swap fees and leverage trading. Pricing on our exchange is supported by an on-chain price feed - this is done with the goal to prevent manipulation and ensure accurate pricing is achieved. AMPED token, $AMP is live on LightLink network. ',
            },
            {
                "role": 'assistant',
                "content": "Okay. I won't bring up what you taught me unless asked.",
            },
        ],
        "temperature": 0.5,
        "repetition_penalty": 1.3,
        "length_penalty": 1.0,
        "max_tokens": 500,
        "stop_token_ids": [128009],
        "model": 'casperhansen/llama-3-70b-instruct-awq',
        "stream": True
    }

def fix_malformed_json(json_string):
    # Remove 'data: ' from the start of each line
    corrected_string = re.sub(r'^data: ', '', json_string, flags=re.MULTILINE)
    return corrected_string
   

    
