# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(619, 678)
        login.setStyleSheet("QWidget {\n"
"    border-radius : \"10px\";\n"
"}")
        self.label = QtWidgets.QLabel(login)
        self.label.setGeometry(QtCore.QRect(0, 0, 619, 678))
        self.label.setStyleSheet("QLabel {\n"
"    background-color : \"#2F2F2F\";\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.logoLbl = QtWidgets.QLabel(login)
        self.logoLbl.setGeometry(QtCore.QRect(168, 50, 272, 99))
        self.logoLbl.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/5 1.png);\n"
"}")
        self.logoLbl.setText("")
        self.logoLbl.setObjectName("logoLbl")
        self.titleLbl = QtWidgets.QLabel(login)
        self.titleLbl.setGeometry(QtCore.QRect(114, 146, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.titleLbl.setFont(font)
        self.titleLbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleLbl.setObjectName("titleLbl")
        self.closeBtn = QtWidgets.QPushButton(login)
        self.closeBtn.setGeometry(QtCore.QRect(560, 30, 25, 25))
        self.closeBtn.setStyleSheet("QPushButton {\n"
"    \n"
"    border-image: url(:/X.png);\n"
"    background-color : transparent;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(0,0,0,0.2);\n"
"}")
        self.closeBtn.setText("")
        self.closeBtn.setObjectName("closeBtn")
        self.loginBtn = QtWidgets.QPushButton(login)
        self.loginBtn.setGeometry(QtCore.QRect(174, 440, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.loginBtn.setFont(font)
        self.loginBtn.setStyleSheet("QPushButton {\n"
"    background-color : \"#0078FF\";\n"
"    border-radius : \"30px\";\n"
"    color : \"#FFFFFF\";\n"
"}\n"
"\n"
"QPush:hover {\n"
"    background-color : \"#0078DD\";\n"
"}")
        self.loginBtn.setObjectName("loginBtn")
        self.label_2 = QtWidgets.QLabel(login)
        self.label_2.setGeometry(QtCore.QRect(182, 510, 271, 99))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(164, 164, 164);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(login)
        self.label_3.setGeometry(QtCore.QRect(201, 547, 221, 99))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(164, 164, 164);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.titleLbl.setText(_translate("login", "Log in to Mirada AI"))
        self.loginBtn.setText(_translate("login", "Login"))
        self.label_2.setText(_translate("login", "Connect your online "))
        self.label_3.setText(_translate("login", "account to log in"))
import resource.resource_rc
